### ISSUE TITLE
Introduce MatchAsync method for Option

### ISSUE THREAD

**Issue by syrotkin** [DigitecGalaxus/Galaxus.Functional#33]
`Option` does not have a `MatchAsync` method. We could add a `MatchAsync` method, so that it could accept asynchronous delegates as parameters.

**Comment by phkiener** [comment]
Hey @syrotkin, thanks for your issue and PR - and sorry for the late feedback!

We're doing some internal changes to the async methods, but I think it's a good idea to provide those async methods for the common methods.. especially since we got `MatchAsync` for other types. I'll move this to the 4.0.0 milestone, we'll release this b efore christmas this year.

**Comment by phkiener** [comment]
To make sure we can release the new version just before christmas this year, I'm gonna detach this from the 4.0.0 milestone. But no worries, this feature will be the reason for 4.1.0 ;)

**Comment by phkiener** [comment]
4.1.0 is released with `Option.MatchAsync` as the single change in it. Thanks a lot for your contribution!
